In [3]:
import pandas as pd
pd.set_option('display.max.rows', 150)

In [4]:
pop_Integrated_Data = pd.read_csv(r"C:\Users\User\Documents\School\FallGrad2023\DW\DataWarehouse_ProjectReport\data\pop_Integrated_Data.csv")
pop_Integrated_Data

,GraduateID,GraduateName,AddressID,MajorID,DegreeID,GPA,GPARankID,SemesterID,YearID,StatusID
0,999,CK. Brown,Denver,Applied Sc,Associate degree,4.0,High,Sum1,1989,International Student
1,961,QT. Brady,Pine Bluff,Computer Sc,Associate degree,3.8,High,Sum2,1987,International Student
2,962,UL. Jones,Little Rock,Computer Sc,Associate degree,3.1,High,Sum2,1984,Out of state
3,970,Bf. Brady,Little Rock,Applied Sc,Associate degree,3.2,High,Sum1,1992,Out of state
4,975,CM. Cook,Little Rock,Biology,Bachelor of Science,2.2,Medium,F,1987,Out of state
5,412,DP. Morty,Atlanta,Biology,Bachelor of Art,3.9,High,S,1984,Out of state
6,971,UK. Yu,Conway,Secondary Ed,Master of Science,3.2,High,F,1990,Out of state
7,989,Li. Mooshe,Atlanta,Secondary Ed,Master of Science,3.9,High,F,1990,Non-of-the above
8,998,Di. Morgan,Conway,Biology,Master of Science,3.9,High,S,1987,Non-of-the above
9,964,YH. Brady,Conway,Applied Sc,Bachelor of Art,3.2,High,Sum1,1987,Non-of-the above
10,977,WT. Brady,Conway,Applied Sc,Bachelor of Art,3.2,High,Sum2,1987,Non-of-the above
11,987,AC. Bank,Conway,Applied Sc,Bachelor of Art,3.2,High,Sum2,1987,Non-of-the above
12,988,TP. Kim,Conway,Elementary Ed,Bachelor of Science,3.2,High,Sum1,1990,Non-of-the above
13,902,CY. Crema,Little Rock,Biology,Bachelor of Science,2.2,Medium,S,1987,Non-of-the above
14,969,D. Abuly,Savannah,Economics,Bachelor of Science,3.9,High,S,1990,NaN
15,968,G. Halky,Atlanta,Business Admin,Bachelor of Science,2.9,Medium,S,1990,NaN
16,967,W.Goast,Savannah,Accounting,Bachelor of Science,4.1,High,F,1990,NaN
17,833,T. Chenty,Conway,Elementary Ed,Associate degree,3.2,High,Sum1,1991,NaN
18,124,U. Algy,Denver,Applied Sc,Associate degree,4.0,High,S,1992,International Student
19,976,YI. Torgan,Conway,Biology,Associate degree,3.9,High,S,1987,International Student
20,100,D. Reddyg,Seattle,Information Sc,Master of Science,2.1,Medium,F,1990,International Student
21,969,Y. Bankrpt,Conway,Applied Sc,Master of Science,3.2,High,Sum1,1987,Out of state
22,901,UI. Wagon,Little Rock,Computer Sc,Master of Science,3.1,High,Sum1,1984,Out of state
23,902,C. Browner,Denver,Applied Sc,Master of Science,4.0,High,S,1989,Out of state
24,777,F. Anglic,Atlanta,Biology,Bachelor of Science,3.9,High,S,1990,Non-of-the above
25,779,BB. Goofan,Atlanta,Chemistry,Bachelor of Science,2.1,Medium,F,1991,Non-of-the above
26,933,GG. Art,Savannah,English,Bachelor of Art,3.1,High,Sum2,1991,Non-of-the above
27,941,BB. Mercy,Savannah,English,Master of Art,4.0,High,Sum2,1991,Non-of-the above
28,667,K. Chen,Conway,Elementary Ed,Doctor of Education,3.2,High,Sum2,1992,Out of state
29,529,M. Yu,Conway,Secondary Ed,Master of Science,3.2,High,S,1990,International Student
30,552,K. Ahmad,Atlanta,Secondary Ed,Doctor of Education,3.9,High,Invalid Date,1987,Out of state
31,687,Y. Morty,Atlanta,Computer Sc,Bachelor of Science,3.9,High,Sum1,1984,Non-of-the above
32,688,Y. Crema,Little Rock,Biology,Associate degree,2.2,Medium,Sum1,1987,Non-of-the above
33,653,C. Alshukri,Denver,Applied Sc,Doctor of Philosophy,4.0,High,F,1991,Out of state
34,986,Q. Brady,Pine Bluff,Computer Sc,Master of Science,3.8,High,S,1987,Non-of-the above
35,579,U. Jones,Little Rock,Computer Sc,Bachelor of Science,3.1,High,S,1984,Non-of-the above
36,200,B. Brady,Little Rock,Applied Sc,Doctor of Philosophy,3.2,High,S,1992,International Student
37,300,C. Cook,Little Rock,Biology,Bachelor of Science,2.2,Medium,Sum1,1987,International Student
38,422,U. Yu,Conway,Secondary Ed,Master of Science,3.2,High,S,1990,Out of state
39,423,U. Mooshe,Atlanta,Secondary Ed,Doctor of Education,3.9,High,Sum1,1990,Out of state
40,401,D. Morgan,Conway,Biology,Bachelor of Science,3.9,High,Sum1,1987,International Student
41,201,W. Brady,Conway,Applied Sc,Doctor of Philosophy,3.2,High,S,1987,International Student
42,202,A. Bank,Conway,Applied Sc,Doctor of Philosophy,3.2,High,Sum1,1987,Non-of-the above
43,415,T. King,Conway,Elementary Ed,Doctor of Education,3.2,High,Sum2,1990,Non-of-the above
44,901,C. Crema,Little Rock,Biology,Associate degree,2.2,Medium,Sum1,1987,Out of state
45,222,D. Abul,Savannah,Economics,Bachelor of Art,3.9,High,Sum2,1990,Non-of-the above
46,333,G. Halk,Atlanta,Business Admin,Master of Business Administration,2.9,Medium,Sum2,1990,Non-of-the above
47,431,W.Goos,Savannah,Accounting,Bachelor of Art,4.1,High,Sum2,1990,Out of state
48,421,T. Chen,Conway,Elementary Ed,Doctor of Education,3.2,High,Sum2,1991,International Student
49,524,U. Alramzy,Denver,Applied Sc,Doctor of Philosophy,4.0,High,F,1992,International Student
50,689,Y. Morgan,Conway,Biology,Bachelor of Science,3.9,High,Sum1,1987,Non-of-the above
51,195,D. Red,Seattle,Information Sc,Bachelor of Science,2.1,Medium,F,1990,Out of state
52,703,Y. Bank,Conway,Applied Sc,Doctor of Philosophy,3.2,High,Sum2,1987,Out of state
53,665,Z. Silver,Seattle,Elementary Ed,Doctor of Education,3.3,High,Sum2,1991,International Student
54,739,A. Moon,Little Rock,Computer Sc,Bachelor of Science,3.1,High,Sum1,1984,Non-of-the above
55,839,Q. Robe,Pine Bluff,Computer Sc,Master of Science,3.8,High,Sum1,1987,Non-of-the above
56,939,U. Wang,Little Rock,Computer Sc,Associate degree,3.1,High,Sum2,1984,Out of state
57,500,K.Bronz,Dallas,Chemistry,Master of Science,3.2,High,Sum1,1988,Out of state
58,132,A. White,Orlando,Computer Sc,Associate degree,3.9,High,Sum2,1992,Non-of-the above
59,232,K. Blue,Little Rock,English,Associate degree,3.1,High,Sum2,1991,International Student
60,352,C. Black,Pine Bluff,Applied Sc,Doctor of Philosophy,3.8,High,Sum2,1990,Out of state
61,600,C. Jones,Dallas,Information Sc,Bachelor of Science,4.0,High,F,1988,Out of state
62,682,Y. Cook,Little Rock,Biology,Bachelor of Science,2.2,Medium,Sum1,1987,Out of state
63,452,N. Brady,Little Rock,Applied Sc,Doctor of Philosophy,3.2,High,Sum2,1988,International Student
64,590,X. Cook,Little Rock,Biology,Associate degree,2.2,Medium,Sum1,1992,Non-of-the above
65,690,D. Brown,Atlanta,Biology,Bachelor of Science,3.9,High,Sum1,1988,Non-of-the above
66,175,K. Glob,Dallas,Applied Sc,Doctor of Philosophy,3.2,High,Sum1,1989,Non-of-the above
67,185,X. Jones,New York,Information Sc,Bachelor of Science,4.0,High,F,1990,Non-of-the above
68,700,A. Boss,Seattle,Elementary Ed,Master of Science,3.3,High,Sum2,1984,International Student
69,800,K. Queen,Conway,Elementary Ed,Doctor of Education,3.2,High,Sum2,1989,Out of state
70,416,T. Gola,Conway,Secondary Ed,Master of Science,3.2,High,S,1990,Non-of-the above
71,420,T. Silver,Seattle,Elementary Ed,Doctor of Education,3.3,High,Sum2,1991,Non-of-the above
72,900,B. Gola,Conway,Secondary Ed,Master of Science,3.2,High,S,1987,International Student
73,955,K. Booth,Atlanta,Secondary Ed,Master of Science,3.9,High,S,1987,Out of state
74,956,C. Jessy,Orlando,Applied Sc,Master of Science,4.0,High,F,1989,Out of state
75,150,A. Cool,Orlando,Computer Sc,Master of Science,3.9,High,Sum2,1986,International Student
76,250,K. Jones,Little Rock,Computer Sc,Bachelor of Science,3.1,High,Sum2,1986,Non-of-the above
77,350,C. Cool,Pine Bluff,Applied Sc,Master of Science,4.0,High,Sum2,1986,Non-of-the above
78,229,M. Katchal,Savannah,Economics,Bachelor of Art,3.0,High,Sum2,1991,Non-of-the above
79,339,H.Poory,Atlanta,Business Admin,Bachelor of Art,3.9,High,Sum2,1987,Non-of-the above
80,439,H. Mishu,Savannah,Accounting,Bachelor of Art,2.8,Medium,Sum2,1987,Out of state
81,329,G. Kooper,Savannah,Accounting,Bachelor of Art,3.0,High,Sum2,1991,Non-of-the above
82,339,M. Bayraq,Savannah,Business Admin,Master of Business Administration,3.9,High,Sum2,1987,Non-of-the above
83,337,N. Mikhy,Savannah,Business Admin,Bachelor of Art,2.8,Medium,Sum2,1987,Out of state
84,650,D. Sorty,Atlanta,Biology,Bachelor of Science,3.9,High,Sum1,1984,Non-of-the above
85,750,K.Gold,Dallas,Applied Sc,Doctor of Philosophy,3.2,High,Sum1,1984,Non-of-the above
86,850,F. Jones,New York,Information Sc,Bachelor of Science,4.0,High,F,1985,International Student
87,950,D. Golden,Seattle,Information Sc,Bachelor of Science,2.1,Medium,F,1985,International Student
88,165,A. Silver,Seattle,Elementary Ed,Master of Science,3.3,High,Sum2,1985,Out of state
89,418,T. Brown,Denver,Applied Sc,Doctor of Philosophy,4.0,High,F,1992,Out of state
90,419,T. Red,Seattle,Information Sc,Bachelor of Science,2.1,Medium,F,1992,Out of state
91,215,K. King,Conway,Elementary Ed,Doctor of Education,3.2,High,Sum2,1984,Non-of-the above
92,315,M. Gola,Conway,English,Master of Science,3.2,High,S,1984,Non-of-the above
93,255,K. Dool,Atlanta,English,Master of Science,3.9,High,Sum1,1986,Non-of-the above
94,299,M. Golab,Seattle,Chemistry,Bachelor of Science,3.0,High,S,1992,Non-of-the above
95,199,K. Duell,Atlanta,Biology,Associate degree,4.0,High,F,1988,International Student
96,473,M. Browny,Seattle,Computer Sc,Doctor of Philosophy,4.0,High,S,1992,International Student
97,407,T. Doolak,Seattle,Business Admin,Master of Business Administration,3.1,High,Sum1,1992,Out of state
98,205,K. Minges,Conway,Elementary Ed,Doctor of Education,3.2,High,Sum2,1984,Non-of-the above
99,305,H. Molar,Conway,Biology,Master of Science,3.2,High,Sum1,1984,Non-of-the above
100,207,K. Goolar,Atlanta,Chemistry,Master of Science,3.9,High,Sum1,1986,Non-of-the above
101,107,M. Kochaal,Savannah,Chemistry,Bachelor of Science,3.9,High,S,1992,Non-of-the above
102,305,M. Searsy,Conway,Biology,Master of Science,3.2,High,Sum1,1984,Non-of-the above
103,207,P. Little,Atlanta,Chemistry,Master of Science,3.9,High,Sum1,1986,Non-of-the above
104,107,M. Big,Little Rock,Chemistry,Bachelor of Science,3.9,High,S,1992,Out of state
105,109,P. Board,Atlanta,Chemistry,Associate degree,4.0,High,F,1988,International Student
106,305,M. Korp,Conway,Biology,Master of Science,3.2,High,Sum1,1984,Non-of-the above
107,109,G. Bear,Little Rock,Biology,Associate degree,4.0,High,F,1988,Out of state
108,591,Z. Kochaal,Savannah,Chemistry,Bachelor of Science,3.9,High,S,1992,Non-of-the above
109,391,X. Searsy,Conway,Biology,Master of Science,3.2,High,Sum1,1984,Non-of-the above
110,201,Y. Little,Atlanta,Chemistry,Master of Science,3.9,High,Sum1,1986,Non-of-the above
111,117,W. Big,Little Rock,Chemistry,Bachelor of Science,3.9,High,S,1992,Out of state
112,612,V. Board,Atlanta,Chemistry,Associate degree,4.0,High,F,1988,International Student
113,305,M. Kartsoo,Conway,Biology,Master of Science,3.2,High,Sum1,1984,Non-of-the above
114,609,N. Gearsal,Little Rock,Biology,Bachelor of Science,4.0,High,F,1988,Out of state
115,615,K. Jiring,Conway,Elementary Ed,Bachelor of Art,3.2,High,Sum2,1984,Non-of-the above
116,715,M. Chendo,Conway,Secondary Ed,Master of Science,3.2,High,S,1984,Non-of-the above
117,855,Z. Megart,Atlanta,Secondary Ed,Master of Science,3.9,High,Sum1,1986,Non-of-the above
118,699,A. Woo,Seattle,Elementary Ed,Bachelor of Art,3.0,High,S,1992,Non-of-the above
119,933,CC. Artian,Atlanta,English,Bachelor of Art,2.9,Medium,Sum2,1991,Non-of-the above
120,941,D. Merdoo,Atlanta,English,Master of Art,2.8,Medium,Sum2,1991,Non-of-the above

In [ ]:
dim_degrees = pd.read_csv(r"C:\Users\User\Documents\School\FallGrad2023\DW\DataWarehouse_ProjectReport\data\FinalDimTables\dim_degrees.csv")
dim_gparank = pd.read_csv(r"C:\Users\User\Documents\School\FallGrad2023\DW\DataWarehouse_ProjectReport\data\FinalDimTables\dim_gparank.csv")
dim_status = pd.read_csv(r"C:\Users\User\Documents\School\FallGrad2023\DW\DataWarehouse_ProjectReport\data\FinalDimTables\dim_status.csv")
dim_time = pd.read_csv(r"C:\Users\User\Documents\School\FallGrad2023\DW\DataWarehouse_ProjectReport\data\FinalDimTables\dim_time.csv")